import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';
const req=createRequire('/Users/jamesroberts/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json');const {chromium}=req('playwright');
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1});const errors=[],badResponses=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)badResponses.push({url:r.url(),status:r.status()});});
const state=()=>page.evaluate(()=>window.coalAtlas.getState());const setRange=async(id,value)=>page.locator('#'+id).evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));},String(value));
async function check(name,fn){await fn();checks.push({name,passed:true});console.log('PASS',name);}
try{
 await page.goto('http://127.0.0.1:8765/',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.coalAtlas?.getState().frameCount>5);await page.waitForTimeout(1700);
 await check('WebGL renders a populated scene',async()=>{const s=await state();assert(s.triangles>100000);assert.equal(s.renderedSeams.length,8);});await page.screenshot({path:'evidence/01-illawarra.png'});
 await check('Thermal-only checkbox filtering updates rendered meshes and markers',async()=>{await page.locator('#met').uncheck();await page.locator('#unknown').uncheck();const s=await state();assert.deepEqual(s.renderedSeams.sort(),['fassifern','greatnorthern','hunter','wallarah']);assert(!s.renderedMines.includes('appin'));assert(s.renderedMines.includes('mtw'));});
 await check('Met-only checkbox filtering preserves the mixed-product mine',async()=>{await page.locator('#met').check();await page.locator('#thermal').uncheck();const s=await state();assert(s.renderedMines.includes('mtw'));assert(s.renderedMines.includes('dendrobium'));assert(!s.renderedMines.includes('myuna'));});
 await check('All filters off shows an honest empty state',async()=>{await page.locator('#met').uncheck();assert.equal((await state()).renderedSeams.length,0);assert(await page.locator('#empty').isVisible());});
 await page.locator('#reset').click();
 await check('Seam selector limits connected mines and transport',async()=>{await page.locator('#seamSelect').selectOption('wongawilli');await page.locator('#showRoutes').check();const s=await state();assert.deepEqual(s.renderedSeams,['wongawilli']);assert(s.renderedRoutes.every(id=>id.startsWith('dendrobium')));assert.equal(s.renderedRoutes.length,2);});
 await check('Opacity and cutaway controls affect scene materials and clipping',async()=>{await setRange('opacity',0);await setRange('slice',60);const s=await state();assert.equal(s.groundOpacity,0);assert(s.clipX<100);await setRange('exaggeration',20);assert.equal((await state()).state.exaggeration,20);});
 await page.locator('#reset').click();await page.locator('#showRoutes').check();await page.locator('#chapters button').nth(1).click();await page.waitForTimeout(1800);
 await check('Sydney chapter shows an unclassified formation and deep-mine context',async()=>{const s=await state();assert.equal(s.chapter,1);assert.equal(s.selected,'central');assert((await page.locator('#detailBody').innerText()).includes('880'));});await page.screenshot({path:'evidence/02-sydney.png'});
 await page.locator('#chapters button').nth(2).click();await page.waitForTimeout(1800);await page.screenshot({path:'evidence/03-lake-macquarie.png'});
 await check('Myuna selection exposes its documented power-station connection',async()=>{await page.locator('#featureSelect').selectOption('myuna');assert((await page.locator('#detailBody').innerText()).includes('Eraring'));await page.locator('#showConnection').click();assert((await state()).renderedRoutes.includes('myuna-eraring'));});
 await page.locator('#chapters button').nth(3).click();await page.locator('#showBores').check();await page.waitForTimeout(1800);await page.screenshot({path:'evidence/04-newcastle.png'});
 await check('Borehole layer toggles independently',async()=>assert((await state()).boreVisible));
 await page.locator('#chapters button').nth(4).click();await page.waitForTimeout(1800);await page.screenshot({path:'evidence/05-hunter.png'});
 await check('Flythrough starts, advances and pauses',async()=>{await setRange('progress',0);await page.locator('#play').click();const a=(await state()).progress;await page.waitForTimeout(1000);assert((await state()).progress>a);await page.locator('#play').click();assert.equal((await state()).playing,false);});
 await check('Scrubbing reaches the Newcastle and final Hunter chapters',async()=>{await setRange('progress',750);assert.equal((await state()).chapter,3);await setRange('progress',1000);assert.equal((await state()).chapter,4);assert((await page.locator('#tourTime').innerText()).startsWith('2:30'));});
 await check('Sources modal contains model limitations and closes with Escape',async()=>{await page.locator('#sources').click();assert(await page.locator('#sourceDialog').isVisible());assert((await page.locator('#sourceBody').innerText()).includes('not a survey'));await page.keyboard.press('Escape');assert(!(await page.locator('#sourceDialog').isVisible()));});
 await check('All viewport and script assets loaded without errors',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(badResponses,[]);});
 await page.setViewportSize({width:390,height:844});await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>window.coalAtlas?.getState().frameCount>5);await page.waitForTimeout(1700);
 await check('Mobile opens on the landscape with no horizontal overflow',async()=>{assert(!(await page.locator('#details').isVisible()));assert(!(await page.locator('#controls').isVisible()));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));});await page.screenshot({path:'evidence/06-mobile.png'});
 await check('Mobile layer drawer supports filtering',async()=>{await page.locator('#toggleControls').click();assert(await page.locator('#controls').isVisible());await page.locator('#met').uncheck();assert(!(await state()).renderedSeams.includes('bulli'));await page.locator('#toggleControls').click();});
 const webmcp=await page.evaluate(()=>({documentSupported:!!document.modelContext?.registerTool,navigatorSupported:!!navigator.modelContext?.registerTool}));
 fs.writeFileSync('evidence/browser-tests.json',JSON.stringify({date:new Date().toISOString(),checks,errors,badResponses,webmcp,finalState:await state()},null,2));
 console.log(`${checks.length} browser checks passed`);
}catch(e){fs.writeFileSync('evidence/browser-tests.json',JSON.stringify({checks,errors,badResponses,failure:e.stack},null,2));throw e;}finally{await browser.close();}
