import fs from 'node:fs';import assert from 'node:assert/strict';import {DEFAULTS,visibleSeams,visibleMines,visibleRoutes,geo,formatTime} from '../dist/model.js';
const a=JSON.parse(fs.readFileSync('dist/data/atlas.json')),t=JSON.parse(fs.readFileSync('dist/data/terrain.json'));const checks=[];function check(name,fn){fn();checks.push({name,passed:true});}
check('Full model has all five journey chapters and eight geological layers',()=>{assert.equal(a.chapters.length,5);assert.equal(a.seams.length,8);});
check('All-use filter includes sixteen mine records',()=>assert.equal(visibleMines(a,DEFAULTS).length,16));
check('Thermal-only retains mixed producer and excludes met-only mines',()=>{const ids=visibleMines(a,{...DEFAULTS,met:false,unknown:false}).map(x=>x.id);assert.deepEqual(ids.sort(),['ashton','bloomfield','bulga','chainvalley','hvo','mandalong','mtw','myuna','ravensworth','rixscreek','unitedwambo','wambo']);});
check('Met-only retains mixed producer and excludes thermal-only mines',()=>{const ids=visibleMines(a,{...DEFAULTS,thermal:false,unknown:false}).map(x=>x.id);assert.deepEqual(ids.sort(),['appin','ashton','bulga','dendrobium','hvo','metropolitan','mtw','ravensworth','rixscreek','unitedwambo']);});
check('Unknown Sydney formation is not misclassified as met or thermal',()=>{for(const tag of ['thermal','met'])assert(!visibleSeams(a,{...DEFAULTS,met:false,thermal:false,unknown:false,[tag]:true}).some(x=>x.id==='central'));});
check('All coal-use switches off produces an empty result',()=>{const s={...DEFAULTS,met:false,thermal:false,unknown:false};assert.equal(visibleSeams(a,s).length,0);assert.equal(visibleMines(a,s).length,0);assert.equal(visibleRoutes(a,s).length,0);});
check('Single-seam selection keeps only connected mines and routes',()=>{const s={...DEFAULTS,seam:'wongawilli'};assert.deepEqual(visibleSeams(a,s).map(x=>x.id),['wongawilli']);assert.deepEqual(visibleMines(a,s).map(x=>x.id),['dendrobium']);assert(visibleRoutes(a,s).every(x=>x.fromId==='dendrobium'));});
check('Every triangle index refers to finite model vertices',()=>{for(const s of a.seams){assert.equal(s.mesh.positions.length%3,0);assert(s.mesh.positions.every(Number.isFinite));assert(s.mesh.indices.every(i=>Number.isInteger(i)&&i>=0&&i<s.mesh.positions.length/3));assert(s.mesh.indices.length>1000);}});
check('Terrain has complete finite elevation grid and meaningful relief',()=>{assert.equal(t.elevations.length,t.nx*t.ny);assert(t.elevations.every(Number.isFinite));assert(Math.max(...t.elevations)>900);assert(Math.min(...t.elevations)<0);});
check('Every route joins existing features with compatible products',()=>{for(const r of a.routes){const m=a.mines.find(x=>x.id===r.fromId),d=a.destinations.find(x=>x.id===r.toId);assert(m&&d);assert(r.tags.every(tag=>m.tags.includes(tag)&&d.tags.includes(tag)));}});
check('Every model feature cites existing source IDs',()=>{const ids=new Set(a.sources.map(s=>s.id));for(const x of [...a.seams,...a.mines,...a.destinations,...a.routes])assert(x.sources.length&&x.sources.every(id=>ids.has(id)));});
check('Northern stratigraphic order is preserved at every grid vertex',()=>{const w=a.seams.find(x=>x.id==='wallarah').mesh.positions,g=a.seams.find(x=>x.id==='greatnorthern').mesh.positions,f=a.seams.find(x=>x.id==='fassifern').mesh.positions;for(let i=1;i<w.length;i+=3)assert(w[i]>g[i]&&g[i]>f[i]);});
check('Southern stratigraphic order is preserved at every grid vertex',()=>{const b=a.seams[0].mesh.positions,g=a.seams[1].mesh.positions,w=a.seams[2].mesh.positions;for(let i=1;i<b.length;i+=3)assert(b[i]>g[i]&&g[i]>w[i]);});
check('Borehole evidence exists, is spatially thinned, and has plausible coordinates',()=>{assert(a.boreTotal>5000);assert(a.bores.length>1000);assert(a.bores.length<a.boreTotal);assert(a.bores.every(b=>b.position.every(Number.isFinite)));});
check('Projection puts Newcastle north of Wollongong and uses metres consistently',()=>{assert(geo(151.78,-32.93)[2]<geo(150.89,-34.43)[2]);assert.equal(geo(151.15,-33.55,880)[1],.88);});
check('Tour timestamp supports the full 150 seconds',()=>assert.equal(formatTime(150),'2:30'));
fs.writeFileSync('evidence/model-tests.json',JSON.stringify({date:new Date().toISOString(),checks},null,2));console.log(`${checks.length} model checks passed`);
