import {createRequire} from 'node:module';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const {chromium}=createRequire('/Users/jamesroberts/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json')('playwright');
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--enable-webgl','--ignore-gpu-blocklist']});
const checks=[],errors=[],bad=[];
const check=async(name,fn)=>{await fn();checks.push({name,passed:true});console.log('PASS',name);};
try{
 const page=await browser.newPage({viewport:{width:1600,height:1000},acceptDownloads:true});
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)bad.push(r.url());});
 await page.goto('http://127.0.0.1:8765/',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.coalGeology?.getState().ready&&window.coalIndustry);await page.waitForTimeout(1700);
 await check('Detailed mapped geology and local elevation load',async()=>{const s=await page.evaluate(()=>window.coalGeology.getState());assert(s.surfaceUnits>1000&&s.localVertices>60000);});
 await check('Selecting a filtered-out mine reveals it and its connections',async()=>{await page.locator('#met').uncheck();await page.locator('#featureSelect').selectOption('dendrobium');await page.locator('#showConnection').click();const s=await page.evaluate(()=>window.coalAtlas.getState());assert(s.renderedMines.includes('dendrobium'));assert(s.renderedRoutes.includes('dendrobium-steelworks'));});
 await page.locator('#reset').click();
 await check('Five-step field guide opens the linked section and stratigraphy',async()=>{await page.locator('#startLesson').click();await page.locator('#nextLesson').click();await page.locator('#nextLesson').click();assert(await page.locator('#sectionPanel').isVisible());assert(await page.locator('#strataPanel').isVisible());assert((await page.locator('#sectionSvg [data-seam]').count())>=3);});
 await page.waitForTimeout(600);await page.screenshot({path:'evidence/v2-section.png'});
 await check('Section selection highlights the same seam in 3D and the column',async()=>{await page.locator('#sectionSvg [data-seam="wongawilli"]').focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>window.coalAtlas.getState().selected),'wongawilli');assert(await page.locator('.strata-unit[data-unit="wongawilli"]').evaluate(e=>e.classList.contains('active')));});
 await check('Stratigraphy highlights published exposures and honestly reports absent mapping',async()=>{
 await page.locator('[data-unit="hawkesbury"]').click();let s=await page.evaluate(()=>coalGeology.getState());assert.equal(s.surfaceFocus.strataId,'hawkesbury');assert(s.surfaceFocus.count>0);assert(await page.locator('#surfaceFocus').isVisible());
 await page.screenshot({path:'evidence/v21-exposures.png'});
 await page.locator('[data-unit="bulli"]').click();s=await page.evaluate(()=>coalGeology.getState());assert.equal(s.surfaceFocus,null);assert((await page.locator('#surfaceFocusText').innerText()).includes('No matching'));
 await page.locator('#clearSurfaceFocus').click();assert(!(await page.locator('#surfaceFocus').isVisible()));
 });
 await check('Mapped section fault crossings expose their actual source description',async()=>{
 await page.locator('#sectionCoordinates summary').click();await page.locator('#aLat').fill('-34.4');await page.locator('#bLat').fill('-34.4');await page.locator('#applySection').click();await page.locator('#sectionCoordinates summary').click();await page.locator('#mappedFaults').check();const s=await page.evaluate(()=>coalGeology.getState());assert(s.crossings.length>0);await page.locator('#sectionFaults summary').click();await page.locator('#sectionFaultList button').first().click();assert((await page.locator('#detailBody').innerText()).includes('no underground fault dip'));assert((await page.locator('#detailBody').innerText()).includes('GSNSW feature'));await page.locator('#mappedFaults').uncheck();
 });
 await check('Borehole evidence preserves reference depths, searchable logs and source flags',async()=>{
 await page.locator('#openBoreholes').click();assert((await page.locator('#boreProfile').innerText()).includes('Kelly Bushing'));await page.locator('#boreSearch').fill('Cordeaux River 1');assert.equal(await page.locator('#boreSelect option').count(),1);
 await page.locator('.bore-table button').filter({hasText:/^Bulli Coal$/}).click();assert((await page.locator('#pickDetail').innerText()).includes('92.5–94.5'));assert((await page.locator('#pickDetail').innerText()).includes('GSNSW_2021'));
 await page.locator('#locateBore').click();await page.waitForTimeout(500);await page.screenshot({path:'evidence/v21-borehole.png'});await page.locator('#boreSearch').fill('not-a-borehole');assert(await page.locator('#boreSelect').isDisabled());await page.locator('#boreSearch').fill('');
 });
 await check('Section overlays show source pick diamonds and open the corresponding borehole',async()=>{
 await page.locator('#transect').selectOption('0');await page.locator('#sectionPicks').check();assert((await page.locator('#sectionSvg [data-pick]').count())>0);await page.locator('#sectionSvg [data-pick]').first().focus();await page.keyboard.press('Enter');assert(await page.locator('#boreProfile').isVisible());assert((await page.locator('#pickWarning').innerText()).includes('not deviation-corrected'));await page.waitForTimeout(500);await page.screenshot({path:'evidence/v21-picks.png'});
 });
 await check('True-scale view and exported SVG include model limitations and source attribution',async()=>{await page.locator('#sectionScale').click();assert((await page.locator('#sectionSvg').textContent()).includes('True scale 1:1'));const downloadPromise=page.waitForEvent('download');await page.locator('#exportSection').click();const d=await downloadPromise;assert.equal(d.suggestedFilename(),'NSW-geological-section.svg');const text=fs.readFileSync(await d.path(),'utf8');assert(text.includes('geometry illustrative')&&text.includes('bioregionalassessments.gov.au'));});
 await check('Custom sections validate endpoints and retain coverage gaps',async()=>{await page.locator('#sectionCoordinates summary').click();await page.locator('#aLon').fill('0');await page.locator('#applySection').click();assert((await page.locator('#sectionMessage').innerText()).includes('distinct points'));await page.locator('#aLon').fill('150.8');await page.locator('#bLon').fill('151.2');await page.locator('#applySection').click();assert((await page.locator('#sectionTitle').innerText()).includes('Custom'));});
 await page.locator('#endLesson').click();await page.locator('#closeSection').click();
 await check('Faults and display separation are explicit independent controls',async()=>{await page.locator('#mappedFaults').check();await page.locator('#explode').fill('50');const s=await page.evaluate(()=>window.coalGeology.getState());assert(s.faults);assert.equal(s.explode,50);});
 await page.locator('#industryToggle').click();
 await check('Statewide inventory contains every downloaded coal record and supports search',async()=>{assert.equal(await page.locator('#mineRows tr').count(),35);await page.locator('#mineSearch').fill('Narrabri');assert.equal(await page.locator('#mineRows tr').count(),1);await page.locator('#mineRows [data-mine]').click();assert((await page.locator('#industryDetail').innerText()).includes('77.5%'));assert((await page.locator('#industryDetail').innerText()).includes('not actual output'));});
 await check('Unknown search has an empty state; CSV exports the filtered records',async()=>{await page.locator('#mineSearch').fill('no-such-mine');assert((await page.locator('#mineRows').innerText()).includes('No mines match'));await page.locator('#mineSearch').fill('Ulan');const p=page.waitForEvent('download');await page.locator('#exportMines').click();const d=await p,text=fs.readFileSync(await d.path(),'utf8');assert(text.includes('Ulan West'));assert.equal(text.trim().split(/\r?\n/).length,3);});
 await page.locator('#mineSearch').fill('');await page.screenshot({path:'evidence/v2-industry.png'});await page.locator('#backGeology').click();
 await check('Mobile lesson, section and strata remain accessible without horizontal page overflow',async()=>{await page.setViewportSize({width:390,height:844});await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>window.coalIndustry);await page.locator('#toggleControls').click();await page.locator('#startLesson').click();await page.locator('#toggleControls').click();await page.locator('#nextLesson').click();await page.locator('#closeGeoDetails').click();await page.locator('#nextLesson').click();assert(await page.locator('#sectionPanel').isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.waitForTimeout(600);assert(await page.evaluate(()=>{const canvas=document.querySelector('canvas'),gl=canvas.getContext('webgl2'),values=new Set(),pixel=new Uint8Array(4);for(let x=20;x<canvas.width;x+=40)for(let y=20;y<canvas.height;y+=40){gl.readPixels(x,y,1,1,gl.RGBA,gl.UNSIGNED_BYTE,pixel);values.add([...pixel].join(','));}return values.size>12;}),'Mobile WebGL view must contain rendered terrain after section resize');await page.screenshot({path:'evidence/v2-mobile.png'});await page.locator('#endLesson').click();await page.locator('#closeSection').click();});
 await check('Mobile borehole search, reference and log remain readable',async()=>{
 await page.locator('#toggleControls').click();await page.locator('#openBoreholes').click();assert(await page.locator('#boreSearch').isVisible());await page.locator('#boreSearch').fill('Cordeaux River 1');assert((await page.locator('#boreProfile').innerText()).includes('Kelly Bushing'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'evidence/v21-mobile-borehole.png'});await page.locator('#closeGeoDetails').click();await page.locator('#toggleControls').click();
 });
 await check('All new datasets and modules loaded without browser errors',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(bad,[]);});
}finally{await browser.close();fs.writeFileSync('evidence/geology-browser-tests.json',JSON.stringify({date:new Date().toISOString(),checks,errors,bad},null,2));}
